### PR TITLE
modify all instances of `CaloTowersCreator` in `customizeHCALinCaloJets`

### PR DESCRIPTION
**Pull request by missirol**
The current version of `customizeHCALinCaloJets` considers only the module `hltTowerMakerForAll`, but I don't see a good reason why other instances of `CaloTowersCreator` should continue to use the older thresholds.

@silviodonato

### CODE REVIEW

**Comment by silviodonato** [comment]
Thank you Marino, you are completely right! For some reason I thought that `hltTowerMakerForAll` was the only instance of `CaloTowersCreator`.
I would prefer to add a new function to keep the possibility to reproduce the old results and to make people fully aware of the change (btw. we should include the new JEC mentioned today at the TSG meeting).

Do you know if this change will affect the CaloJet (ie. if we need new CaloJet JECs)?

**Comment by missirol** [comment]
> Do you know if this change will affect the CaloJet (ie. if we need new CaloJet JECs)?

I don't think so. I have to check better what these extra CaloTowers do, but I don't think they affect the HLT CaloJets.

**Comment by missirol** [comment]
> I would prefer to add a new function to keep the possibility to reproduce the old results and to make people fully aware of the change

No problem, we can close this PR.

**Comment by missirol** [comment]
For reference, this is what I see in the HLT combined table (`/dev/CMSSW_13_0_0/HLT/V76`).

 - `hltStoppedHSCPTowerMakerForAll`: used only in the Paths `HLT_UncorrectedJetE*_NoBPTX*_v*` of GRun, which use their own _uncorrected_ CaloJets;

 - `hltTowerMakerEcal`: used only in the Path `HLT_ECALHT800_v` of GRun, which cuts on HT computed from these CaloTowers;

 - `hltTowerMakerForAllBeamHaloCleaned`: used to compute a beam-halo-cleaned version of raw CaloMET in the Paths `HLT_PFMET*200_BeamHaloCleaned_v` of GRun;

 - `hltTowerMakerForAll`: used for the standard AK4/8 HLT CaloJets (several Paths of GRun and other subtables);

 - `hltTowerMakerForAllCPUOnly`: CPU-only replica of `hltTowerMakerForAll`, used in the Path `AlCa_PFJet40_CPUOnly_v` of GRun.

Assuming the above is correct, I think that updates to the 'extra' CaloTowers (first 3 bullets) don't require any changes to the conditions in the GT.

With the current customisation (which ignores `hltTowerMakerForAllCPUOnly`), we should maybe see a disagreement between `AlCa_PFJet40_CPUOnly_v` and `AlCa_PFJet40_v`.

**Comment by silviodonato** [comment]
Thank you Marino, luckly this bug should have a small effect.
I updated the code, including also the latest JEC and PFHC presented in the last TSG meeting (`customizeHLTFor2023_v4_fromFile`)

**Pull request closed without merging**
